<template><div><!--
 * @Author: ylmzfun ylmzfun@163.com
 * @Date: 2025-10-04 07:38:51
 * @LastEditors: ylmzfun ylmzfun@163.com
 * @LastEditTime: 2025-10-04 07:38:51
 * @FilePath: /Users/ylmzfun/Documents/study/note/poetry/序记/小石潭记.md
 * @Description: 古文辞章汇编 - 传承中华文化经典
-->
<h1 id="小石潭记" tabindex="-1"><a class="header-anchor" href="#小石潭记"><span>小石潭记</span></a></h1>
<p>标题：小石潭记
作者：柳宗元（唐）
体裁：记（散文）</p>
<p>导言</p>
<ul>
<li>主题：写景与心境，孤寂情怀的寄托。</li>
<li>背景：永州贬谪时期名篇，精工描摹与独特意境。</li>
</ul>
<p>版本与推荐</p>
<ul>
<li>《柳河东集》、中华书局点校本。</li>
</ul>
<p>文本</p>
<p>从小丘西行百二十步，隔篁竹，闻水声，如鸣珮环，心乐之。伐竹取道，下见小潭，水尤清冽。全石以为底，近岸，卷石底以出，为坻，为屿，为嵁，为岩。青树翠蔓，蒙络摇缀，参差披拂。</p>
<p>潭中鱼可百许头，皆若空游无所依。日光下澈，影布石上，佁然不动；俶尔远逝，往来翕忽，似与游者相乐。</p>
<p>潭西南而望，斗折蛇行，明灭可见。其岸势犬牙差互，不可知其源。</p>
<p>坐潭上，四面竹树环合，寂寥无人，凄神寒骨，悄怆幽邃。以其境过清，不可久居，乃记之而去。</p>
<p>同游者：吴武陵，龚古，余弟宗玄。隶而从者，崔氏二小生：曰恕己，曰奉壹。</p>
<p>注释与译</p>
<p><strong>注释</strong></p>
<ol>
<li><strong>小丘</strong>：指小石城山，在永州西南。</li>
<li><strong>篁竹</strong>：竹林。篁，竹子的总称。</li>
<li><strong>如鸣珮环</strong>：像玉佩玉环相撞的声音。珮，同&quot;佩&quot;。</li>
<li><strong>心乐之</strong>：心里为此感到快乐。乐，意动用法。</li>
<li><strong>伐竹取道</strong>：砍伐竹子，开辟道路。</li>
<li><strong>水尤清冽</strong>：水格外清澈。冽，清凉。</li>
<li><strong>全石以为底</strong>：整块石头做为潭底。以为，把...当作。</li>
<li><strong>卷石底以出</strong>：石底有些部分翻卷过来露出水面。卷，弯曲。</li>
<li><strong>坻</strong>：水中高地。</li>
<li><strong>屿</strong>：小岛。</li>
<li><strong>嵁</strong>：不平的岩石。</li>
<li><strong>蒙络摇缀</strong>：覆盖缠绕摇动连结。蒙，覆盖；络，缠绕；摇，摇动；缀，连结。</li>
<li><strong>参差披拂</strong>：长短不齐，随风飘动。参差，长短不齐；披拂，随风飘动。</li>
<li><strong>可百许头</strong>：大约有一百来条。许，表示约数。</li>
<li><strong>皆若空游无所依</strong>：都好像在空中游动，什么依靠也没有。</li>
<li><strong>日光下澈</strong>：阳光直照到水底。澈，透明。</li>
<li><strong>影布石上</strong>：鱼影映在石头上。布，映，分布。</li>
<li><strong>佁然不动</strong>：呆呆地一动不动。佁然，呆呆的样子。</li>
<li><strong>俶尔远逝</strong>：忽然向远处游去。俶尔，忽然。</li>
<li><strong>往来翕忽</strong>：来来往往轻快敏捷。翕忽，轻快敏捷的样子。</li>
<li><strong>斗折蛇行</strong>：像北斗星那样曲折，像蛇那样蜿蜒前行。</li>
<li><strong>明灭可见</strong>：时隐时现。明灭，时明时暗。</li>
<li><strong>犬牙差互</strong>：像狗的牙齿那样参差不齐。差互，交错不齐。</li>
<li><strong>凄神寒骨</strong>：使人感到心神凄凉，寒气透骨。凄，使...凄凉；寒，使...寒冷。</li>
<li><strong>悄怆幽邃</strong>：寂静得使人感到忧伤，幽深远离尘世。悄怆，忧伤的样子；幽邃，幽深。</li>
<li><strong>以其境过清</strong>：因为这里的环境过于凄清。以，因为。</li>
<li><strong>隶而从者</strong>：跟着同去的。隶，附属，跟从。</li>
</ol>
<p><strong>翻译</strong></p>
<p>从小石城山向西走一百二十步，隔着竹林，听到水声，好像玉佩玉环相撞的声音，心里很高兴。砍倒竹子，开辟出一条道路，向下走就看见一个小潭，潭水格外清澈。小潭以整块石头为底，靠近岸边，石底有些部分翻卷过来露出水面，成为坻、屿、嵁、岩等各种不同的形状。青翠的树木，翠绿的藤蔓，覆盖缠绕，摇动连结，参差不齐，随风飘动。</p>
<p>潭中的鱼大约有一百来条，都好像在空中游动，什么依靠也没有。阳光直照到水底，鱼的影子映在石头上，呆呆地一动不动；忽然又向远处游去，来来往往，轻快敏捷，好像和游人相互取乐。</p>
<p>向潭的西南方向望去，看到溪水像北斗星那样曲折，像蛇那样蜿蜒前行，时隐时现。溪岸的形状像狗的牙齿那样参差不齐，不能知道溪水的源头。</p>
<p>坐在潭边，四面被竹子和树木围绕，寂静空旷，没有人迹，使人感到心神凄凉，寒气透骨，寂静得使人感到忧伤，幽深远离尘世。因为这里的环境过于凄清，不能长久停留，于是记下这番景致就离开了。</p>
<p>同游的人有：吴武陵，龚古，我的弟弟宗玄。跟着同去的有姓崔的两个小书童：一个叫恕己，一个叫奉壹。</p>
<p>赏析要点</p>
<p><strong>历史背景</strong>
《小石潭记》是柳宗元&quot;永州八记&quot;中的第四篇，写于唐宪宗元和四年（809年）。当时柳宗元因参与王叔文政治革新失败而被贬永州司马，心情抑郁。他借游览山水来排遣内心的愁苦，寄情山水，抒发被贬后的凄苦心境。</p>
<p><strong>结构层次</strong></p>
<ol>
<li><strong>发现小潭</strong>：闻声寻源，初见小潭</li>
<li><strong>潭中景物</strong>：描写潭水、游鱼的清澈灵动</li>
<li><strong>溪流走向</strong>：写小溪的曲折幽深</li>
<li><strong>环境氛围</strong>：写潭上环境的凄清幽邃</li>
<li><strong>记录同游</strong>：点明游伴，结束全文</li>
</ol>
<p><strong>写景技巧</strong></p>
<ol>
<li><strong>移步换景</strong>：按游览顺序，层次分明地描写景物</li>
<li><strong>点面结合</strong>：既有整体描写，又有细节刻画</li>
<li><strong>动静结合</strong>：静态的潭水与动态的游鱼相映成趣</li>
<li><strong>声色并茂</strong>：水声如鸣环，色彩清澈明净</li>
<li><strong>比喻生动</strong>：用&quot;鸣珮环&quot;、&quot;斗折蛇行&quot;、&quot;犬牙差互&quot;等比喻</li>
</ol>
<p><strong>情景交融</strong></p>
<ol>
<li><strong>以景写情</strong>：通过描写小潭的清幽来表达内心的孤寂</li>
<li><strong>情随景迁</strong>：从初见时的&quot;心乐之&quot;到后来的&quot;凄神寒骨&quot;</li>
<li><strong>借景抒情</strong>：&quot;以其境过清，不可久居&quot;暗示心境的凄凉</li>
<li><strong>情景一体</strong>：景物的凄清与作者心境的凄苦完美融合</li>
</ol>
<p><strong>语言特色</strong></p>
<ol>
<li><strong>简洁精练</strong>：用词准确，句式简洁，无一冗词</li>
<li><strong>音韵和谐</strong>：多用双声叠韵词，如&quot;参差&quot;、&quot;悄怆&quot;等</li>
<li><strong>色彩鲜明</strong>：青树翠蔓，日光下澈，层次分明</li>
<li><strong>感情真挚</strong>：字里行间流露出真实的情感体验</li>
</ol>
<p><strong>修辞手法</strong></p>
<ol>
<li><strong>比喻</strong>：&quot;如鸣珮环&quot;、&quot;斗折蛇行&quot;、&quot;犬牙差互&quot;</li>
<li><strong>拟人</strong>：&quot;似与游者相乐&quot;</li>
<li><strong>对偶</strong>：&quot;青树翠蔓，蒙络摇缀，参差披拂&quot;</li>
<li><strong>通感</strong>：&quot;凄神寒骨&quot;，将视觉感受转化为心理感受</li>
</ol>
<p><strong>艺术特色</strong></p>
<ol>
<li><strong>写景精细</strong>：对小潭景物的描写细致入微，形象生动</li>
<li><strong>层次清晰</strong>：按空间顺序和时间顺序安排材料</li>
<li><strong>详略得当</strong>：重点描写潭水和游鱼，其他景物略写</li>
<li><strong>意境深远</strong>：营造出清幽凄美的意境</li>
</ol>
<p><strong>思想内容</strong></p>
<ol>
<li><strong>寄情山水</strong>：通过游览山水来排遣内心的苦闷</li>
<li><strong>孤独心境</strong>：表达了被贬后的孤独和凄苦</li>
<li><strong>审美情趣</strong>：体现了作者对自然美的敏锐感受</li>
<li><strong>人生感慨</strong>：&quot;不可久居&quot;暗含对人生际遇的感慨</li>
</ol>
<p><strong>文学价值</strong></p>
<ol>
<li><strong>山水文学典范</strong>：是中国古代山水游记的经典之作</li>
<li><strong>写景技巧高超</strong>：为后世山水文学提供了范本</li>
<li><strong>情景交融完美</strong>：达到了情与景的高度统一</li>
<li><strong>语言艺术精湛</strong>：简洁而富有表现力</li>
</ol>
<p><strong>现实意义</strong>
《小石潭记》不仅是一篇优美的山水游记，更是作者心灵的写照。它告诉我们，即使在人生的低谷，也要保持对美的敏感和追求，通过与自然的对话来净化心灵，获得精神上的慰藉。同时，它也展现了中国古代文人&quot;寄情山水&quot;的文化传统和审美情趣。</p>
</div></template>


