<template><div><!--
 * @Author: ylmzfun ylmzfun@163.com
 * @Date: 2025-10-01 15:55:02
 * @LastEditors: ylmzfun ylmzfun@163.com
 * @LastEditTime: 2025-10-01 19:27:12
 * @FilePath: /诗词/诗词/唐诗/蜀道难.md
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
-->
<h1 id="蜀道难" tabindex="-1"><a class="header-anchor" href="#蜀道难"><span>蜀道难</span></a></h1>
<p>作者：李白（唐）
体裁：乐府古题</p>
<p>导言</p>
<ul>
<li>奇峭瑰丽，夸饰山川险峻，以景寓情。</li>
</ul>
<p>底本与版本</p>
<ul>
<li>推荐检索：中华书局《李白集》点校本；旁证《全唐诗》。</li>
</ul>
<h2 id="原文" tabindex="-1"><a class="header-anchor" href="#原文"><span>原文</span></a></h2>
<p><strong>蜀道难</strong></p>
<p>噫吁嚱，危乎高哉！蜀道之难，难于上青天！
蚕丛及鱼凫，开国何茫然！
尔来四万八千岁，不与秦塞通人烟。
西当太白有鸟道，可以横绝峨眉巅。
地崩山摧壮士死，然后天梯石栈相钩连。
上有六龙回日之高标，下有冲波逆折之回川。
黄鹤之飞尚不得过，猿猱欲度愁攀援。
青泥何盘盘，百步九折萦岩峦。
扪参历井仰胁息，以手抚膺坐长叹。
问君西游何时还？畏途巉岩不可攀。
但见悲鸟号古木，雄飞雌从绕林间。
又闻子规啼夜月，愁空山。
蜀道之难，难于上青天，使人听此凋朱颜！
连峰去天不盈尺，枯松倒挂倚绝壁。
飞湍瀑流争喧豗，砯崖转石万壑雷。
其险也如此，嗟尔远道之人胡为乎来哉！
剑阁峥嵘而崔嵬，一夫当关，万夫莫开。
所守或匪亲，化为狼与豺。
朝避猛虎，夕避长蛇；磨牙吮血，杀人如麻。
锦城虽云乐，不如早还家。
蜀道之难，难于上青天，侧身西望长咨嗟！</p>
<h2 id="注释" tabindex="-1"><a class="header-anchor" href="#注释"><span>注释</span></a></h2>
<ul>
<li><strong>噫吁嚱</strong>：感叹词，表示惊叹。</li>
<li><strong>蚕丛及鱼凫</strong>：传说中古蜀国的两位君主。</li>
<li><strong>开国何茫然</strong>：建国的情况多么渺茫难知。</li>
<li><strong>四万八千岁</strong>：极言时间久远，非实指。</li>
<li><strong>秦塞</strong>：秦地的关塞。</li>
<li><strong>太白</strong>：太白山，在陕西。</li>
<li><strong>鸟道</strong>：只有鸟才能飞过的道路。</li>
<li><strong>峨眉巅</strong>：峨眉山顶。</li>
<li><strong>地崩山摧壮士死</strong>：指五丁开山的传说。</li>
<li><strong>天梯石栈</strong>：在悬崖峭壁上凿成的道路。</li>
<li><strong>六龙回日</strong>：传说太阳神驾六龙，遇高山而回车。</li>
<li><strong>高标</strong>：高峰。</li>
<li><strong>冲波逆折</strong>：水流冲击回旋。</li>
<li><strong>猿猱</strong>：猿类。</li>
<li><strong>青泥</strong>：青泥岭，在甘肃、陕西边界。</li>
<li><strong>盘盘</strong>：曲折回环的样子。</li>
<li><strong>百步九折</strong>：一百步要转九个弯。</li>
<li><strong>扪参历井</strong>：手可摸到参、井二星宿，形容山高。</li>
<li><strong>胁息</strong>：屏住呼吸。</li>
<li><strong>抚膺</strong>：拍胸。</li>
<li><strong>畏途</strong>：可怕的道路。</li>
<li><strong>巉岩</strong>：险峻的山岩。</li>
<li><strong>子规</strong>：杜鹃鸟。</li>
<li><strong>凋朱颜</strong>：红颜变色，指脸色因恐惧而变白。</li>
<li><strong>连峰去天不盈尺</strong>：山峰距离天空不到一尺。</li>
<li><strong>飞湍瀑流</strong>：急流瀑布。</li>
<li><strong>喧豗</strong>：水声巨大。</li>
<li><strong>砯崖转石</strong>：山崖上滚落巨石。</li>
<li><strong>万壑雷</strong>：千万条山谷中响起雷鸣般的声音。</li>
<li><strong>剑阁</strong>：剑门关。</li>
<li><strong>峥嵘而崔嵬</strong>：高峻险要的样子。</li>
<li><strong>一夫当关，万夫莫开</strong>：一个人把守关口，一万个人也打不开。</li>
<li><strong>所守或匪亲</strong>：守关的人如果不是亲信。</li>
<li><strong>化为狼与豺</strong>：变成像狼豺一样凶恶。</li>
<li><strong>磨牙吮血</strong>：磨着牙齿吸人血。</li>
<li><strong>锦城</strong>：成都的别称。</li>
<li><strong>咨嗟</strong>：叹息。</li>
</ul>
<h2 id="译文" tabindex="-1"><a class="header-anchor" href="#译文"><span>译文</span></a></h2>
<p>啊呀呀，多么高峻多么险要！蜀道的艰难，比登上青天还要难！
蚕丛和鱼凫两位君主，开国的情况多么渺茫难知！
从那时到现在有四万八千年了，不与秦地的关塞有人烟往来。
西边太白山有鸟儿能飞过的小道，可以横渡峨眉山顶。
地崩山摧压死了壮士，然后才有天梯石栈相互钩连。
上有使六龙拉的太阳车也要绕行的高峰，下有冲击回旋的急流。
黄鹤飞翔尚且不能飞过，猿猴想要攀越也发愁无处攀援。
青泥岭多么曲折回环，百步之内要转九个弯绕着山峦。
手可摸到参井星宿，紧张得屏住呼吸，用手拍着胸膛坐下长叹。
问你西游什么时候回来？这可怕的道路，险峻的山岩难以攀登。
只见悲鸟在古树上哀鸣，雄鸟雌鸟相随飞绕在林间。
又听见杜鹃在月夜里啼叫，声音在空旷的山中回荡。
蜀道的艰难，比登上青天还要难，使人听了这话红颜变色！
连绵的山峰离天空不到一尺，枯松倒挂在绝壁上。
急流瀑布争相喧闹奔腾，撞击山崖使石头滚动发出万壑雷鸣。
就是这样险要，唉，你这远道而来的人为什么要到这里来呢！
剑阁高峻险要，一个人把守关口，一万个人也打不开。
守关的人如果不是朝廷的亲信，就会变成像狼豺一样的叛逆。
早晨要躲避猛虎，晚上要躲避长蛇；它们磨着牙齿吸人血，杀人如割草。
锦城虽然说是快乐的地方，不如早早回家。
蜀道的艰难，比登上青天还要难，侧身向西望着长长地叹息！</p>
<h2 id="赏析" tabindex="-1"><a class="header-anchor" href="#赏析"><span>赏析</span></a></h2>
<p>《蜀道难》是李白的代表作之一，也是中国古典诗歌中描写山川险峻的杰作。</p>
<p><strong>创作背景：</strong>
此诗作于李白初入长安时期，可能有劝阻友人入蜀的用意，也可能是借蜀道之险抒发对政治险恶的感慨。</p>
<p><strong>主题思想：</strong></p>
<ol>
<li><strong>山川险峻</strong>：通过对蜀道险峻的描写，展现了大自然的雄奇壮美。</li>
<li><strong>政治隐喻</strong>：以蜀道之险暗喻政治道路的险恶和人生道路的艰难。</li>
<li><strong>人生感慨</strong>：表达了对人生际遇和政治现实的深刻思考。</li>
</ol>
<p><strong>艺术特色：</strong></p>
<ol>
<li><strong>想象奇特</strong>：运用丰富的想象，将蜀道的险峻描绘得惊心动魄。</li>
<li><strong>夸张手法</strong>：大量运用夸张，如&quot;难于上青天&quot;、&quot;连峰去天不盈尺&quot;等。</li>
<li><strong>神话传说</strong>：融入蚕丛鱼凫、五丁开山、六龙回日等神话传说，增强了诗歌的神秘色彩。</li>
<li><strong>音韵铿锵</strong>：运用&quot;噫吁嚱&quot;等感叹词，增强了诗歌的音乐性和感染力。</li>
</ol>
<p><strong>表现手法：</strong></p>
<ol>
<li><strong>反复咏叹</strong>：三次重复&quot;蜀道之难，难于上青天&quot;，层层递进，加强语势。</li>
<li><strong>虚实结合</strong>：既有实写蜀道险峻，又有虚写政治险恶。</li>
<li><strong>动静结合</strong>：静态的山川描写与动态的水流、鸟兽描写相结合。</li>
<li><strong>对比手法</strong>：锦城的快乐与蜀道的险恶形成对比。</li>
</ol>
<p><strong>结构特点：</strong>
全诗可分为三个部分：</p>
<ol>
<li><strong>开篇点题</strong>：以感叹句开头，奠定全诗基调。</li>
<li><strong>具体描写</strong>：详细描写蜀道的险峻和恐怖。</li>
<li><strong>劝告结尾</strong>：劝告远道之人不如早归。</li>
</ol>
<p><strong>语言特色：</strong></p>
<ol>
<li><strong>气势磅礴</strong>：语言雄浑有力，气势磅礴。</li>
<li><strong>音韵和谐</strong>：大量运用双声叠韵，音调铿锵。</li>
<li><strong>词汇丰富</strong>：运用大量形容词和动词，描写生动形象。</li>
</ol>
<p><strong>思想意义：</strong></p>
<ol>
<li><strong>现实关怀</strong>：通过对蜀道险峻的描写，表达了对现实政治的关注。</li>
<li><strong>人文精神</strong>：体现了诗人对人生命运的深刻思考。</li>
<li><strong>艺术价值</strong>：在艺术表现上达到了很高的水准，影响了后世无数诗人。</li>
</ol>
<p><strong>文学地位：</strong></p>
</div></template>


